version: "3.8"

services:
  mlflow:
    build: .
    container_name: mlflow
    ports:
      - "5000:5000"
    volumes:
      - ./mlruns:/app/mlruns
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow:5000
  
  ds:
    build: .
    container_name: ds
    command: python /app/logistic-regression-iris-example.py
    volumes:
      - ./scripts:/app
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow:5000
    depends_on:
      - mlflow